/*---------------------------------------------------------------------------------------------
 *  Copyright (c) 2026 ShortestPath IDE contributors.
 *  Licensed under the GPL-3.0-or-later license. See LICENSE in the project root for license information.
 *--------------------------------------------------------------------------------------------*/

const managedCompilerSuffix = '/user/globalstorage/shortestpath.shortestpath-setup/toolchains/winlibs/mingw64/bin/g++.exe';
const managedClangdSuffix = '/user/globalstorage/shortestpath.shortestpath-setup/toolchains/clangd/clangd_22.1.6/bin/clangd.exe';
const managedCompilerProfileSuffix = /\/user\/(?:profiles\/[^/]+\/)?globalstorage\/shortestpath\.shortestpath-setup\/toolchains\/winlibs\/mingw64\/bin\/g\+\+\.exe$/;
const managedClangdProfileSuffix = /\/user\/(?:profiles\/[^/]+\/)?globalstorage\/shortestpath\.shortestpath-setup\/toolchains\/clangd\/clangd_22\.1\.6\/bin\/clangd\.exe$/;

export const managedClangdConfigMarker = '# Managed by ShortestPath IDE setup.';

function normalizePortablePath(value: string): string {
	return value.replaceAll('\\', '/').replace(/\/+/g, '/').toLowerCase();
}

function hasManagedSuffix(value: string, suffix: string): boolean {
	const normalized = normalizePortablePath(value);
	return suffix === managedCompilerSuffix
		? managedCompilerProfileSuffix.test(normalized)
		: suffix === managedClangdSuffix
			? managedClangdProfileSuffix.test(normalized)
			: normalized.endsWith(suffix);
}

/** Return the portable data root for either the default or a named VS Code profile. */
export function getPortableDataRoot(globalStoragePath: string): string | undefined {
	return /^(.*\/data)\/user-data\/user(?:\/profiles\/[^/]+)?\/globalstorage(?:\/|$)/i.exec(normalizePortablePath(globalStoragePath))?.[1];
}

/** Rebase a path only when it points at a ShortestPath-managed portable toolchain. */
export function rebaseManagedToolchainPath(value: string, compiler: string, clangd: string): string | undefined {
	if (hasManagedSuffix(value, managedCompilerSuffix)) {
		return compiler;
	}
	if (hasManagedSuffix(value, managedClangdSuffix)) {
		return clangd;
	}
	return undefined;
}

/** Rebase a clangd query-driver argument while preserving unrelated arguments. */
export function rebaseManagedQueryDriver(argument: string, compiler: string): string {
	const prefix = '--query-driver=';
	if (!argument.startsWith(prefix)) {
		return argument;
	}

	const drivers = argument.slice(prefix.length).split(',');
	const rebasedDrivers = drivers.map(driver => {
		const value = driver.trim();
		if (!hasManagedSuffix(value, managedCompilerSuffix)) {
			return driver;
		}
		return driver.replace(value, compiler);
	});
	return `${prefix}${rebasedDrivers.join(',')}`;
}

function isLegacyGeneratedClangdConfig(content: string): boolean {
	return /^CompileFlags:\r?\n  Add:\r?\n    - -std=c\+\+(?:11|14|17|20|23)\r?\n    - -Wall\r?\n    - -Wextra\r?\n    - "-Drsize_t=size_t"\r?\n    - "-D__STDC_WANT_LIB_EXT1__=1"\r?\n    - "-D__float128=long double"\r?\n    - -U__SIZEOF_FLOAT128__\r?\n  BuiltinHeaders: QueryDriver\r?\n  Compiler: ".+"\r?\n\r?\nCompletion:\r?\n  HeaderInsertion: Never\r?\n\r?\nIndex:\r?\n  Background: Build\r?\n$/.test(content);
}

/** Rebase the compiler line in a .clangd file generated by ShortestPath setup. */
export function rebaseGeneratedClangdConfig(content: string, compiler: string): string {
	const hasManagedMarker = content.startsWith(`${managedClangdConfigMarker}\n`) || content.startsWith(`${managedClangdConfigMarker}\r\n`);
	if (!hasManagedMarker && !isLegacyGeneratedClangdConfig(content)) {
		return content;
	}

	return content.replace(/^([ \t]*Compiler:[ \t]*)(["']?)(.+?)\2[ \t]*$/m, (line, prefix: string, quote: string, value: string) => {
		if (!hasManagedSuffix(value, managedCompilerSuffix)) {
			return line;
		}
		return `${prefix}${quote}${compiler.replaceAll('\\', '/')}${quote}`;
	});
}
